name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Quick syntax check
        run: |
          python -m py_compile bot/main.py